import {
  Merge,
  Scissors,
  FileDown,
  Minimize2,
  Pencil,
  PenTool,
  Droplets,
  RotateCw,
  Trash2,
  FileOutput,
  LayoutGrid,
  Crop,
  Hash,
  ShieldOff,
  GitCompare,
  Languages,
  ScanLine,
  Wrench,
  Lock,
  Unlock,
  Image,
  FileText,
  Presentation,
  Table,
  Globe,
  Camera,
  Eraser,
  Wand2,
  Type,
  Images,
  Tags,
  Palette,
  Layers,
  Maximize,
  PanelTop,
  Stamp,
  Shuffle,
  Grid2x2,
  Ruler,
  Volume2,
  MessageCircle,
  type LucideIcon,
} from 'lucide-react';

export interface ToolConfig {
  id: string;
  name: string;
  description: string;
  route: string;
  icon: LucideIcon;
  color: string;
  bgColor: string;
  category: ToolCategory;
}

export type ToolCategory =
  | 'organize'
  | 'edit'
  | 'optimize'
  | 'convert-to-pdf'
  | 'convert-from-pdf'
  | 'security';

export const categoryLabels: Record<ToolCategory, string> = {
  organize: 'Organize & Manage',
  edit: 'Edit & Annotate',
  optimize: 'Optimize',
  'convert-to-pdf': 'Convert to PDF',
  'convert-from-pdf': 'Convert from PDF',
  security: 'Security',
};

export const tools: ToolConfig[] = [
  // Organize & Manage
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into one document',
    route: '/merge-pdf',
    icon: Merge,
    color: '#6366F1',
    bgColor: '#EEF2FF',
    category: 'organize',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Separate one page or a whole set into independent files',
    route: '/split-pdf',
    icon: Scissors,
    color: '#F97316',
    bgColor: '#FFF7ED',
    category: 'organize',
  },
  {
    id: 'remove-pages',
    name: 'Remove Pages',
    description: 'Delete specific pages from your PDF document',
    route: '/remove-pages',
    icon: Trash2,
    color: '#EF4444',
    bgColor: '#FEF2F2',
    category: 'organize',
  },
  {
    id: 'extract-pages',
    name: 'Extract Pages',
    description: 'Pull specific pages out into a new PDF',
    route: '/extract-pages',
    icon: FileOutput,
    color: '#14B8A6',
    bgColor: '#F0FDFA',
    category: 'organize',
  },
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    description: 'Sort, add, and delete pages to reorder your PDF',
    route: '/organize-pdf',
    icon: LayoutGrid,
    color: '#8B5CF6',
    bgColor: '#F5F3FF',
    category: 'organize',
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate pages within your PDF document',
    route: '/rotate-pdf',
    icon: RotateCw,
    color: '#3B82F6',
    bgColor: '#EFF6FF',
    category: 'organize',
  },
  {
    id: 'crop-pdf',
    name: 'Crop PDF',
    description: 'Define margins and trim areas on your PDF',
    route: '/crop-pdf',
    icon: Crop,
    color: '#22C55E',
    bgColor: '#F0FDF4',
    category: 'organize',
  },
  {
    id: 'add-page-numbers',
    name: 'Page Numbers',
    description: 'Add page numbers with custom position and format',
    route: '/add-page-numbers',
    icon: Hash,
    color: '#64748B',
    bgColor: '#F8FAFC',
    category: 'organize',
  },
  {
    id: 'resize-pdf',
    name: 'Resize PDF',
    description: 'Change PDF page size, add page margins and padding',
    route: '/resize-pdf',
    icon: Maximize,
    color: '#0D9488',
    bgColor: '#CCFBF1',
    category: 'organize',
  },
  {
    id: 'header-footer-pdf',
    name: 'Header & Footer',
    description: 'Apply custom text labels, dates, or metadata to PDF pages',
    route: '/header-footer-pdf',
    icon: PanelTop,
    color: '#6366F1',
    bgColor: '#E0E7FF',
    category: 'organize',
  },
  {
    id: 'bates-numbering',
    name: 'Bates Numbering',
    description: 'Apply legal Bates stamps with custom prefixes to multiple files',
    route: '/bates-numbering',
    icon: Stamp,
    color: '#0F766E',
    bgColor: '#CCFBF1',
    category: 'organize',
  },
  {
    id: 'alternate-mix',
    name: 'Alternate & Mix',
    description: 'Mix pages from 2 or more documents, alternating between them',
    route: '/alternate-mix',
    icon: Shuffle,
    color: '#C026D3',
    bgColor: '#FAE8FF',
    category: 'organize',
  },
  {
    id: 'n-up-pdf',
    name: 'N-up PDF',
    description: 'Print multiple pages per sheet (e.g., 2-up, 4-up on A4)',
    route: '/n-up-pdf',
    icon: Grid2x2,
    color: '#1D4ED8',
    bgColor: '#DBEAFE',
    category: 'organize',
  },

  // Edit & Annotate
  {
    id: 'edit-pdf',
    name: 'Edit PDF',
    description: 'Add text, images, shapes, and annotations to your PDF',
    route: '/edit-pdf',
    icon: Pencil,
    color: '#0077C2',
    bgColor: '#E0F2FE',
    category: 'edit',
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Sign yourself or request electronic signatures',
    route: '/sign-pdf',
    icon: PenTool,
    color: '#7C3AED',
    bgColor: '#F5F3FF',
    category: 'edit',
  },
  {
    id: 'watermark-pdf',
    name: 'Watermark',
    description: 'Stamp an image or text watermark over your PDF',
    route: '/watermark-pdf',
    icon: Droplets,
    color: '#06B6D4',
    bgColor: '#ECFEFF',
    category: 'edit',
  },
  {
    id: 'redact-pdf',
    name: 'Redact PDF',
    description: 'Permanently remove sensitive information from your PDF',
    route: '/redact-pdf',
    icon: ShieldOff,
    color: '#DC2626',
    bgColor: '#FEF2F2',
    category: 'edit',
  },
  {
    id: 'compare-pdf',
    name: 'Compare PDF',
    description: 'Show a side-by-side comparison to spot changes',
    route: '/compare-pdf',
    icon: GitCompare,
    color: '#2563EB',
    bgColor: '#EFF6FF',
    category: 'edit',
  },
  {
    id: 'translate-pdf',
    name: 'Translate PDF',
    description: 'AI-powered translation while keeping layout intact',
    route: '/translate-pdf',
    icon: Languages,
    color: '#059669',
    bgColor: '#ECFDF5',
    category: 'edit',
  },
  {
    id: 'remove-annotations',
    name: 'Remove Annotations',
    description: 'Permanently remove comments, highlights, and annotations from your PDF',
    route: '/remove-annotations',
    icon: Eraser,
    color: '#F43F5E',
    bgColor: '#FFF1F2',
    category: 'edit',
  },
  {
    id: 'pdf-to-speech',
    name: 'PDF to Speech',
    description: 'Listen to your PDF documents using text-to-speech',
    route: '/pdf-to-speech',
    icon: Volume2,
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    category: 'edit',
  },
  {
    id: 'chat-with-pdf',
    name: 'Chat with PDF',
    description: 'Summarize or ask questions about your PDF contents',
    route: '/chat-with-pdf',
    icon: MessageCircle,
    color: '#3B82F6',
    bgColor: '#DBEAFE',
    category: 'edit',
  },
  {
    id: 'edit-metadata',
    name: 'Edit Metadata',
    description: 'Change PDF Author, Title, Keywords, Subject and other metadata fields',
    route: '/edit-metadata',
    icon: Tags,
    color: '#8B5CF6',
    bgColor: '#F5F3FF',
    category: 'edit',
  },
  {
    id: 'flatten-pdf',
    name: 'Flatten PDF',
    description: 'Make fillable forms and annotations read-only',
    route: '/flatten-pdf',
    icon: Layers,
    color: '#6366F1',
    bgColor: '#EEF2FF',
    category: 'edit',
  },

  // Optimize
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce file size while optimizing for quality',
    route: '/compress-pdf',
    icon: Minimize2,
    color: '#EF4444',
    bgColor: '#FEF2F2',
    category: 'optimize',
  },
  {
    id: 'repair-pdf',
    name: 'Repair PDF',
    description: 'Recover data from damaged or corrupt PDF files',
    route: '/repair-pdf',
    icon: Wrench,
    color: '#D97706',
    bgColor: '#FFFBEB',
    category: 'optimize',
  },
  {
    id: 'ocr-pdf',
    name: 'OCR PDF',
    description: 'Convert scanned PDFs to searchable and selectable text',
    route: '/ocr-pdf',
    icon: ScanLine,
    color: '#7C3AED',
    bgColor: '#F5F3FF',
    category: 'optimize',
  },
  {
    id: 'pdf-cleaner',
    name: 'PDF Cleaner',
    description: 'Strip out unwanted layers, hidden text, and metadata assets',
    route: '/pdf-cleaner',
    icon: Wand2,
    color: '#10B981',
    bgColor: '#D1FAE5',
    category: 'optimize',
  },
  {
    id: 'grayscale-pdf',
    name: 'Grayscale PDF',
    description: 'Convert PDF text and images to black and white or grayscale',
    route: '/grayscale-pdf',
    icon: Palette,
    color: '#475569',
    bgColor: '#F1F5F9',
    category: 'optimize',
  },

  // Convert to PDF
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert JPG images to PDF documents',
    route: '/jpg-to-pdf',
    icon: Image,
    color: '#EAB308',
    bgColor: '#FEFCE8',
    category: 'convert-to-pdf',
  },
  {
    id: 'word-to-pdf',
    name: 'WORD to PDF',
    description: 'Convert DOC and DOCX files to PDF',
    route: '/word-to-pdf',
    icon: FileText,
    color: '#2563EB',
    bgColor: '#EFF6FF',
    category: 'convert-to-pdf',
  },
  {
    id: 'powerpoint-to-pdf',
    name: 'POWERPOINT to PDF',
    description: 'Convert PPT and PPTX slideshows to PDF',
    route: '/powerpoint-to-pdf',
    icon: Presentation,
    color: '#EA580C',
    bgColor: '#FFF7ED',
    category: 'convert-to-pdf',
  },
  {
    id: 'excel-to-pdf',
    name: 'EXCEL to PDF',
    description: 'Convert XLS and XLSX spreadsheets to PDF',
    route: '/excel-to-pdf',
    icon: Table,
    color: '#16A34A',
    bgColor: '#F0FDF4',
    category: 'convert-to-pdf',
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Convert webpages in HTML to PDF format',
    route: '/html-to-pdf',
    icon: Globe,
    color: '#0891B2',
    bgColor: '#ECFEFF',
    category: 'convert-to-pdf',
  },

  // Convert from PDF
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert each PDF page into a JPG image',
    route: '/pdf-to-jpg',
    icon: Image,
    color: '#CA8A04',
    bgColor: '#FEFCE8',
    category: 'convert-from-pdf',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to WORD',
    description: 'Convert PDF files to editable DOCX documents',
    route: '/pdf-to-word',
    icon: FileText,
    color: '#1D4ED8',
    bgColor: '#EFF6FF',
    category: 'convert-from-pdf',
  },
  {
    id: 'pdf-to-powerpoint',
    name: 'PDF to POWERPOINT',
    description: 'Convert PDF files to editable PPTX slideshows',
    route: '/pdf-to-powerpoint',
    icon: Presentation,
    color: '#C2410C',
    bgColor: '#FFF7ED',
    category: 'convert-from-pdf',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to EXCEL',
    description: 'Pull data straight from PDFs into spreadsheets',
    route: '/pdf-to-excel',
    icon: Table,
    color: '#15803D',
    bgColor: '#F0FDF4',
    category: 'convert-from-pdf',
  },
  {
    id: 'pdf-to-text',
    name: 'PDF to TEXT',
    description: 'Extract raw text content into a clean text file',
    route: '/pdf-to-text',
    icon: Type,
    color: '#4B5563',
    bgColor: '#F3F4F6',
    category: 'convert-from-pdf',
  },
  {
    id: 'extract-images',
    name: 'Extract Images',
    description: 'Extract all embedded image assets from your PDF',
    route: '/extract-images',
    icon: Images,
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    category: 'convert-from-pdf',
  },
  {
    id: 'pdf-to-pdfa',
    name: 'PDF to PDF/A',
    description: 'Transform PDF for long-term archiving (ISO standard)',
    route: '/pdf-to-pdfa',
    icon: FileDown,
    color: '#9333EA',
    bgColor: '#FAF5FF',
    category: 'convert-from-pdf',
  },

  // Security
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove PDF password security to access your file',
    route: '/unlock-pdf',
    icon: Unlock,
    color: '#16A34A',
    bgColor: '#F0FDF4',
    category: 'security',
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Encrypt your PDF documents with a password',
    route: '/protect-pdf',
    icon: Lock,
    color: '#DC2626',
    bgColor: '#FEF2F2',
    category: 'security',
  },
  {
    id: 'measure-pdf',
    name: 'Measure PDF',
    description: 'Measure distances and areas on your PDF pages with precision',
    route: '/measure-pdf',
    icon: Ruler,
    color: '#8B5CF6',
    bgColor: '#F5F3FF',
    category: 'edit',
  },
  {
    id: 'deskew-pdf',
    name: 'Deskew PDF',
    description: 'Straighten crooked or tilted pages from scanned documents',
    route: '/deskew-pdf',
    icon: RotateCw,
    color: '#3B82F6',
    bgColor: '#EFF6FF',
    category: 'optimize',
  },
  {
    id: 'scan-to-pdf',
    name: 'Scan to PDF',
    description: 'Simulate a scanned look or process images from browser camera into PDF',
    route: '/scan-to-pdf',
    icon: Camera,
    color: '#0EA5E9',
    bgColor: '#F0F9FF',
    category: 'convert-to-pdf',
  },
];

export const getToolsByCategory = (category: ToolCategory): ToolConfig[] => {
  return tools.filter((tool) => tool.category === category);
};

export const getToolById = (id: string): ToolConfig | undefined => {
  return tools.find((tool) => tool.id === id);
};
